### ISSUE TITLE
could not load perl module SAPNW, wrong device

### ISSUE THREAD

**Issue by picoroma** [lausser/check_sap_health#20]
I have recently update my  NAGIOS OS server from Ubuntu 18.04 to 20.04

After this OS update I noticed problem with "check_sap_health" plugin.
First I have some PERL module missing:
JSON
Data::...::date
After I have Installed these 2 modules with cpan the 
check_sap_health -V give me the correct results :
check_sap_health $Revision: 3.0.0.2 $ [http://labs.consol.de/nagios/check_sap_health]

But any check commands give me the error:
CRITICAL - could not load perl module SAPNW, wrong device

I have also updated the saprfcsdk to the latest version 7.50 P11 but the results do not change
Any suggestion?

**Comment by lausser** [comment]
Hi,
i have no idea. The error happens when the module "sapnwrfc" is loaded. So first it must be made sure that this works flawlessly.
```
lausser@HULSE:~/git$ perl -e "use sapnwrfc"
Can't locate sapnwrfc.pm ....
```
There must be no output at all, then you can proceed with check_sap_health.
You can try with strace if loading the module requires some files/shared libs, which are not found and maybe it's LD_LIBRARY_PATH.

**Comment by nomoresecrets** [comment]
@picoroma did you solve the issue? if so - how?
